import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "@/lib/redux/provider";
import { Toaster } from "react-hot-toast";
import Header from "@/components/layout/Header";
import ProtectRoute from "@/components/GaurdRouteComponent";
import SideBar from "@/components/SideBar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
 <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
          <ProtectRoute />
          <Header />
          <Toaster />
          <div className="flex">
             <SideBar />

             <main className="flex-1 p-6 bg-gray-50 min-h-screen">
              {children}
            </main>
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
